name: Copy luci-tailsc

on:
  workflow_dispatch:

jobs:
  copy-luci-theme-argon:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Target Repository
      uses: actions/checkout@v3

    - name: Clone luci-app-tailscale-community
      run: |
        git clone --depth 1 --branch master https://github.com/Tokisaki-Galaxy/luci-app-tailscale-community.git temp-luci-app-tailscale-community
        mkdir -p luci-app-tailscale-community
        cp -r temp-luci-app-tailscale-community/luci-app-tailscale-community/* ./luci-app-tailscale-community/
        rm -rf temp-luci-app-tailscale-community

    - name: Commit Changes
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git add luci-app-tailscale-community
        git commit -m "zzzzz"

    - name: Push Changes to Main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin main
